name: every week

on:
  workflow_dispatch:
  schedule:
    # 실제 스케쥴 작업이 시작될 cron을 등록하면 됩니다.
    # 크론은 https://crontab.guru/ 여기서 확인하면 좋을 것 같습니다.
    # 이 크론은 화요일 13시 0분에 실행됩니다.
    - cron: "0 13 * * 2"

env:
  USER_ID: ${{ secrets.USER_ID }}
  USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
  PURCHASE_QUANTITY: ${{ secrets.PURCHASE_QUANTITY }}
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

jobs:
  check-secret:
    runs-on: ubuntu-latest
    outputs:
      my-key: ${{ steps.success.outputs.defined }}
    steps:
      - id: fail
        if: "${{ env.USER_ID == '' || env.USER_PASSWORD == '' }}"
        run: echo "동행복권 아이디, 비밀번호를 Github -> Settings -> Secrets 에서 입력해주세요."

      - id: success
        if: "${{ env.USER_ID != '' && env.USER_PASSWORD != '' }}"
        run: echo "::set-output name=defined::true"

  cron:
    if: needs.check-secret.outputs.my-key == 'true'
    runs-on: ubuntu-latest
    needs: [check-secret]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install
        # NOTE: this pins the action to a specific commit sha for security
        # reasons but you can also use a version tag if desired. For example:
        # ianwalter/puppeteer-container@v4.0.0
        uses: ianwalter/puppeteer-container@acc52cd2334ad9eaf6e1974562d263e0a711b7e8
        with:
          args: npm i

      - name: Start
        uses: ianwalter/puppeteer-container@acc52cd2334ad9eaf6e1974562d263e0a711b7e8
        with:
          args: npm start
